version: '3'

networks:
  user_manager_app_test:
    driver: bridge

services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
#    ports:
#      - "8080:8080"
#    depends_on:
#      - redis
#      - mysql
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      #      HOME_PROJECT: /home/rcrespo/github.com/rcrespodev
      #      HOME_PROJECT: /app
      LOG_FILE_PATH: ./logs/errors.log
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret
      MYSQL_DATABASE: user_manager
      JSON_MESSAGES: /app/pkg/kernel/cqrs/returnLog/repository/messages.json
    networks:
      - user_manager_app_test