version: '3'

networks:
  user_manager_app:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    restart: on-failure
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret
      MYSQL_DATABASE: user_manager
    networks:
      - user_manager_app
  mysql:
    image: mysql
    container_name: user_manager_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_secret
      MYSQL_DATABASE: user_manager
    networks:
      - user_manager_app

  redis:
    image: "redis:7.0.0-alpine"
    command: redis-server --save 20 1
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - user_manager_app