FROM golang:1.18-alpine

# Install git
RUN set -ex; \
    apk update; \
    apk add --no-cache git

# Set working directory
WORKDIR /app_test
#COPY . ./

# Build Go Binary
RUN set -ex; \
CGO_ENABLED=0 GOOS=linux go build -o ./bin/main-linux cmd/web/main.go \
go test ./... ;